include $(srctree)/scripts/Makefile.rules

cleanobjs += $(progs)
_allobjs :=

define prog_rule
obj-$(1) := $$(patsubst %/,%/built-in.a,$$(obj-$(1)))
$(1): $$(obj-$(1))
	$$(call kecho,LD,$$@)
	$$(Q)$$(CC) $$(LDFLAGS) -o $$@ \
		$$(filter-out %.a,$$^) \
		-Wl,--whole-archive $$(filter %.a,$$^) -Wl,--no-whole-archive \
		$$(LDLIBS)
cleanobjs += $$(obj-$(1)) $$(patsubst %.o,%.d,$$(obj-$(1)))
_allobjs += $$(obj-$(1))
endef

$(foreach prog,$(progs),$(eval $(call prog_rule,$(prog))))

.PHONY: all clean

all: $(progs)

clean:
	$(call kecho,CLEAN,.)
	$(Q)rm -f $(filter-out %/built-in.a,$(cleanobjs))
	$(Q)$(foreach d,$(sort $(patsubst %/built-in.a,%,$(filter %/built-in.a,$(cleanobjs)))), \
		$(MAKE) -C $(d) -f $(srctree)/scripts/Makefile.subdir_build clean; )

-include $(patsubst %.o,%.d,$(filter %.o,$(_allobjs)))
