name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    #- name: Install Build uses
    #  run: sudo apt install build-essential binutils
      
    - name: Start Make
      run: make

    - name: Build artifact
      run: |
           mkdir build
           cp out/lsh build/lsh-x86_64

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LSH x86_64
        path: build/lsh-x86_64
